- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
  become: yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
  become: yes

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes

# Add docker repository
- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  become: yes

# Install docker 
- name: Update apt and install docker-ce
  apt: update_cache=yes name=docker-ce state=latest
  become: yes

# Enable  docker service
- name: "enable docker service"
  service:
          name: docker
          enabled: yes
  become: yes

# restart docker service
- name: " restart docker service"
  service:
          name: docker
          enabled: yes

  become: true